version: "3.8"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
